apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    app: influxdb
  annotations:
    metallb.universe.tf/allow-shared-ip: metallb-system
spec:
  selector:
    app: influxdb
  ports:
  - name: influxdb
    port: 8086
    targetPort: 8086
  