apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
      app: grafana
  annotations:
    metallb.universe.tf/allow-shared-ip: metallb-system
spec:
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  selector:
    app: grafana
  ports:
    - port: 3000
      name: http
      protocol: TCP
      targetPort: 3000