apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: metallb-system
spec:
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  selector:
    app: phpmyadmin
  ports:
    - port: 5000
      name: http
      protocol: TCP
      targetPort: 5000
