apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: metallb-system
spec:
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
    - port: 5050
      name: http
      protocol: TCP
      targetPort: 5050